In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('car_data.csv')
data.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [3]:
data.rename(columns={'name':'brand'}, inplace=True)

In [4]:
data.sample(5)

,brand,year,selling_price,km_driven,fuel,seller_type,transmission,owner
1966,Maruti Wagon R LXI BS IV,2011,250000,50000,Petrol,Individual,Manual,First Owner
581,Chevrolet Beat LT Option,2016,239000,41000,Petrol,Dealer,Manual,First Owner
3906,Maruti Swift VXI,2019,550000,51000,Petrol,Individual,Manual,First Owner
2196,Chevrolet Tavera Neo 3 Max 9 Str BSIII,2014,400000,120000,Diesel,Individual,Manual,Second Owner
225,Mahindra Renault Logan 1.5 DLS,2008,89999,213000,Diesel,Individual,Manual,First Owner

In [5]:
print(data.columns)

Index(['brand', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner'],
      dtype='object')

In [6]:
print(data.columns[data.columns.duplicated()])

Index([], dtype='object')

In [7]:
data = data.loc[:, ~data.columns.duplicated()]

In [8]:
data['brand'].value_counts().head()

brand
Maruti Swift Dzire VDI    69
Maruti Alto 800 LXI       59
Maruti Alto LXi           47
Hyundai EON Era Plus      35
Maruti Alto LX            35
Name: count, dtype: int64

In [9]:
data['fuel'].value_counts()

fuel
Diesel      2153
Petrol      2123
CNG           40
LPG           23
Electric       1
Name: count, dtype: int64

In [10]:
data['seller_type'].value_counts()

seller_type
Individual          3244
Dealer               994
Trustmark Dealer     102
Name: count, dtype: int64

In [11]:
data['transmission'].value_counts()

transmission
Manual       3892
Automatic     448
Name: count, dtype: int64

# One Hot Encoding using pandas

In [12]:
pd.get_dummies(data, columns=['fuel','transmission','seller_type'])

,brand,year,selling_price,km_driven,owner,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,transmission_Automatic,transmission_Manual,seller_type_Dealer,seller_type_Individual,seller_type_Trustmark Dealer
0,Maruti 800 AC,2007,60000,70000,First Owner,False,False,False,False,True,False,True,False,True,False
1,Maruti Wagon R LXI Minor,2007,135000,50000,First Owner,False,False,False,False,True,False,True,False,True,False
2,Hyundai Verna 1.6 SX,2012,600000,100000,First Owner,False,True,False,False,False,False,True,False,True,False
3,Datsun RediGO T Option,2017,250000,46000,First Owner,False,False,False,False,True,False,True,False,True,False
4,Honda Amaze VX i-DTEC,2014,450000,141000,Second Owner,False,True,False,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Second Owner,False,True,False,False,False,False,True,False,True,False
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Second Owner,False,True,False,False,False,False,True,False,True,False
4337,Maruti 800 AC BSIII,2009,110000,83000,Second Owner,False,False,False,False,True,False,True,False,True,False
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,First Owner,False,True,False,False,False,False,True,False,True,False
4339,Renault KWID RXT,2016,225000,40000,First Owner,False,False,False,False,True,False,True,False,True,False

# K-1 One Hot Encoding

In [13]:
pd.get_dummies(data, columns=['fuel','transmission','seller_type'], drop_first=True)

,brand,year,selling_price,km_driven,owner,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,transmission_Manual,seller_type_Individual,seller_type_Trustmark Dealer
0,Maruti 800 AC,2007,60000,70000,First Owner,False,False,False,True,True,True,False
1,Maruti Wagon R LXI Minor,2007,135000,50000,First Owner,False,False,False,True,True,True,False
2,Hyundai Verna 1.6 SX,2012,600000,100000,First Owner,True,False,False,False,True,True,False
3,Datsun RediGO T Option,2017,250000,46000,First Owner,False,False,False,True,True,True,False
4,Honda Amaze VX i-DTEC,2014,450000,141000,Second Owner,True,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Second Owner,True,False,False,False,True,True,False
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Second Owner,True,False,False,False,True,True,False
4337,Maruti 800 AC BSIII,2009,110000,83000,Second Owner,False,False,False,True,True,True,False
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,First Owner,True,False,False,False,True,True,False
4339,Renault KWID RXT,2016,225000,40000,First Owner,False,False,False,True,True,True,False

# One Hot Encoding using sklearn in python

In [14]:
data.head()

,brand,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [15]:
X = data[['brand', 'year', 'km_driven', 'fuel', 'seller_type',
          'transmission', 'owner']]
y = data['selling_price']

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [17]:
from sklearn.preprocessing import OneHotEncoder

### ohe=OneHotEncoder(drop='first'/'ifbinary', sparse_output=True/False, dtype=np.int64)
### when sparse_output=True then it give me the result in 1D Array
### when spase_output=False then it give me the result in 2D Array
### drop='first' remove the first column in the encoding columns
### drop='ifbinary' remove if feature has two value only
### we can dtype to chnage the data types

In [18]:
# ohe=OneHotEncoder()
# ohe=OneHotEncoder(drop='first', sparse=True/False)
ohe=OneHotEncoder(drop='first',sparse_output=False)
ohe.fit_transform(X_train[['fuel', 'transmission', 'seller_type']])
ohe.fit_transform(X_test[['fuel', 'transmission', 'seller_type']])

array([[0., 0., 1., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 1., 0.],
       ...,
       [1., 0., 0., 1., 1., 0.],
       [0., 0., 1., 1., 1., 0.],
       [0., 0., 1., 1., 1., 0.]])

In [19]:
ohe.fit_transform(X_train[['fuel', 'transmission', 'seller_type']])
ohe.fit_transform(X_test[['fuel', 'transmission', 'seller_type']])

array([[0., 0., 1., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 1., 0.],
       ...,
       [1., 0., 0., 1., 1., 0.],
       [0., 0., 1., 1., 1., 0.],
       [0., 0., 1., 1., 1., 0.]])

### if sparse_output=True then use convert it into 2d array by using toarray() function in this code
### ohe.fit_transform(X_train[['fuel', 'transmission', 'seller_type']]).toarray()

In [20]:
X_train_new=ohe.fit_transform(X_train[['fuel', 'transmission', 'seller_type']])
X_test_new=ohe.fit_transform(X_test[['fuel', 'transmission', 'seller_type']])

In [21]:
import numpy as np
X_train_final = np.hstack((
    X_train[['brand', 'year', 'km_driven', 'owner']].values,
    X_train_new
))

X_test_final = np.hstack((
    X_test[['brand', 'year', 'km_driven', 'owner']].values,
    X_test_new
))

In [22]:
X_train_final.shape

(3472, 11)

# OneHotEncoding with Top Categories

In [23]:
data['brand'].value_counts()

brand
Maruti Swift Dzire VDI                            69
Maruti Alto 800 LXI                               59
Maruti Alto LXi                                   47
Hyundai EON Era Plus                              35
Maruti Alto LX                                    35
                                                  ..
Honda Brio 1.2 S Option MT                         1
Mahindra Bolero Power Plus Plus Non AC BSIV PS     1
Tata Indigo LS BSII                                1
Force One EX                                       1
Chevrolet Aveo 1.4 LT BSIV                         1
Name: count, Length: 1491, dtype: int64

In [24]:
counts=data['brand'].value_counts()
data['brand'].nunique
threshold=10
other = counts[counts <= threshold].index

In [25]:
pd.get_dummies(data['brand'].replace(other, 'Other_Brand'),
    drop_first=True,
    dtype=int)

,Audi A6 2.0 TDI Premium Plus,BMW X5 xDrive 30d xLine,Chevrolet Beat Diesel LS,Chevrolet Beat Diesel LT,Chevrolet Beat LT,Chevrolet Beat LT Option,Chevrolet Spark 1.0 LS,Ford Ecosport 1.5 DV5 MT Titanium,Ford Figo Diesel Titanium,Hyundai Creta 1.6 CRDi SX,...,Mercedes-Benz C-Class Progressive C 220d,Other_Brand,Renault Duster 85PS Diesel RxL,Renault KWID 1.0 RXT Optional,Renault KWID RXT,Skoda Laura Ambiente 2.0 TDI CR MT,Tata Indica GLS BS IV,Tata Indigo CR4,Tata New Safari DICOR 2.2 EX 4x2,Toyota Fortuner 4x2 AT
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4335,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4336,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4337,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4338,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4339,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0