In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('customer.csv')
data.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [3]:
data.sample(5)

    age  gender review education purchased
28   48    Male   Poor    School        No
31   22  Female   Poor    School       Yes
23   96  Female   Good    School        No
14   15    Male   Poor        PG       Yes
16   59    Male   Poor        UG       Yes

In [4]:
cat_col=[col for col in data.columns if data[col].dtype == 'O']
cat_data=data[cat_col]
cat_data.head()

   gender   review education purchased
0  Female  Average    School        No
1  Female     Poor        UG        No
2  Female     Good        PG        No
3  Female     Good        PG        No
4  Female  Average        UG        No

### Age  Numerical Columns
### Genger - Nomial Columns
### Review - Ordinal Columns
### Education - Ordinal Columns
### Purchased -  Nomial Columns

In [5]:
data=data.iloc[:,2:]
data.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
for col in data.columns :
  print(data[col].value_counts())

review
Poor       18
Good       18
Average    14
Name: count, dtype: int64
education
PG        18
School    16
UG        16
Name: count, dtype: int64
purchased
No     26
Yes    24
Name: count, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:,0:2], data.iloc[:,-1], test_size=0.2, random_state=2)

In [8]:
X_train.columns

Index(['review', 'education'], dtype='object')

In [9]:
y_train

24    Yes
48    Yes
17    Yes
12     No
27     No
33    Yes
16    Yes
2      No
25     No
14    Yes
30     No
5     Yes
32    Yes
1      No
29    Yes
35    Yes
41    Yes
19    Yes
37    Yes
10    Yes
4      No
6      No
3      No
20    Yes
26     No
38     No
21     No
42    Yes
31    Yes
34     No
7     Yes
49     No
11    Yes
18     No
43     No
22    Yes
8      No
45    Yes
15     No
40     No
Name: purchased, dtype: object

In [10]:
from sklearn.preprocessing import OrdinalEncoder
os=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [11]:
os.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [12]:
X_train_encode=os.transform(X_train)
X_test_encode=os.transform(X_test)

In [13]:
os.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [15]:
X_train=pd.DataFrame(data=X_train_encode , columns=X_train.columns)
X_test=pd.DataFrame(data=X_test_encode , columns=X_test.columns)

In [16]:
X_train.head()

   review  education
0     1.0        2.0
1     2.0        1.0
2     0.0        1.0
3     0.0        0.0
4     0.0        2.0

In [17]:
X_test.head()

   review  education
0     2.0        1.0
1     2.0        2.0
2     0.0        0.0
3     2.0        1.0
4     1.0        0.0

In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [19]:
y_train_encode=le.transform(y_train)
y_test_encode=le.transform(y_test)

In [21]:
y_train=pd.DataFrame(data=y_train_encode)
y_test=pd.DataFrame(data=y_test_encode)

In [23]:
y_train.head()

   0
0  1
1  1
2  1
3  0
4  0

In [24]:
le.classes_

array(['No', 'Yes'], dtype=object)